{{- $kinds := list }}
{{- range .Values.constraints  }}
{{ $kinds = append $kinds .kind }}
{{- end }}

{{- $files := .Files }}
{{- range $kinds | uniq }}
{{ $files.Get (printf "generated/%v.yaml" .) }}
---
{{- end }}
