apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: init-container-read-only-root-fs
spec:
  match:
    scope: Namespaced
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod"]
  applyTo:
    - groups: [""]
      versions: ["v1"]
      kinds: ["Pod"]
  location: "spec.initContainers[name:*].securityContext.readOnlyRootFilesystem"
  parameters:
    assign:
      value: true
