constraints:
  - kind: K8sHttpsOnly
    name: https-only
  - kind: K8sPodPriorityClass
    name: pod-priority-class

assigns:
  - name: container-read-only-root-fs
  - name: container-drop-capabilities
