{{- $prefix := .Values.namePrefix }}

{{- range .Values.modifySets }}
{{- $modifySetData := $.Files.Get (printf "generated/%s.yaml" .name) | toString | fromYaml }}
apiVersion: mutations.gatekeeper.sh/v1beta1
kind: ModifySet
metadata:
  name: {{ $prefix }}{{ required "Assign name needs to be set" .name }}
spec:
  applyTo: {{- $modifySetData.spec.applyTo | toYaml | nindent 4 }}
  location: {{ quote $modifySetData.spec.location }}
  parameters: {{- $modifySetData.spec.parameters | toYaml | nindent 4 }}
---
{{- end }}
