name: check-generate

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      #- name: Install yq
      #- name: Install kustomize
      - name: Run Makefile
        run: make generate
