name: check-generate

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Makefile
        run: |
          wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
          mv yq_linux_amd64 yq
          chmox +x yq
          PATH=$PATH:./yq
          make generate
