name: opa-test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  opa-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run opa test
      uses: b4b4r07/action-opa@master
