name: publish-helm-chart
on:
  release:
    types:
      - published
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Get GitHub Tag
        id: get_tag
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chart_version: ${{ steps.get_tag.outputs.tag }}
          app_version: ${{ steps.get_tag.outputs.tag }}
